import type { SerializedNode } from "../types";

export const sampleNodes: SerializedNode[] = [
  {
    id: "1:1",
    name: "Checkout",
    type: "FRAME",
    width: 390,
    height: 844,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    parentId: null,
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: true,
    childCount: 8,
  },
  {
    id: "2:1",
    name: "Account balance",
    type: "TEXT",
    width: 200,
    height: 20,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#777777", rgb: { r: 119, g: 119, b: 119 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    fontSize: 16,
    fontWeight: 400,
    characters: "Account balance",
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
  {
    id: "2:2",
    name: "Legal caption",
    type: "TEXT",
    width: 180,
    height: 12,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#111111", rgb: { r: 17, g: 17, b: 17 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    fontSize: 10,
    fontWeight: 400,
    lineHeightPx: 11,
    characters: "Fees may apply",
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
  {
    id: "3:1",
    name: "Icon button",
    type: "COMPONENT",
    width: 18,
    height: 18,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#111111", rgb: { r: 17, g: 17, b: 17 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    componentName: "IconButton",
    variantProperties: { State: "Hover" },
    componentSetVariants: ["State=Default", "State=Hover"],
    isComponent: true,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 1,
  },
  {
    id: "3:2",
    name: "Primary button",
    type: "INSTANCE",
    width: 140,
    height: 40,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#0B57D0", rgb: { r: 11, g: 87, b: 208 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    componentName: "Button",
    variantProperties: { State: "Default" },
    componentSetVariants: ["State=Default", "State=Hover", "State=Focus"],
    isComponent: false,
    isInstance: true,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: true,
    childCount: 1,
  },
  {
    id: "4:1",
    name: "Email input / placeholder",
    type: "INSTANCE",
    width: 280,
    height: 40,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, opacity: 1, visible: true }],
    strokes: [{ type: "SOLID", hex: "#CCCCCC", rgb: { r: 204, g: 204, b: 204 }, opacity: 1, visible: true }],
    strokeWeight: 1,
    characters: "Enter email",
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    componentName: "Text field",
    isComponent: false,
    isInstance: true,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
  {
    id: "5:1",
    name: "Success / error status",
    type: "ELLIPSE",
    width: 12,
    height: 12,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#22C55E", rgb: { r: 34, g: 197, b: 94 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    parentId: "1:1",
    ancestorFills: [],
    background: { hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, reliable: true },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
  {
    id: "6:1",
    name: "Hero photo",
    type: "RECTANGLE",
    width: 358,
    height: 180,
    opacity: 1,
    visible: true,
    fills: [{ type: "IMAGE", opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    parentId: "1:1",
    ancestorFills: [],
    background: {
      hex: "#FFFFFF",
      rgb: { r: 255, g: 255, b: 255 },
      reliable: false,
      reason: "Image fill",
    },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    imageIntent: "unknown",
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
  {
    id: "7:1",
    name: "Title on photo",
    type: "TEXT",
    width: 200,
    height: 28,
    opacity: 1,
    visible: true,
    fills: [{ type: "SOLID", hex: "#FFFFFF", rgb: { r: 255, g: 255, b: 255 }, opacity: 1, visible: true }],
    strokes: [],
    strokeWeight: 0,
    fontSize: 22,
    fontWeight: 700,
    characters: "Pay now",
    parentId: "1:1",
    ancestorFills: [[{ type: "IMAGE", opacity: 1, visible: true }]],
    background: {
      hex: "#FFFFFF",
      rgb: { r: 255, g: 255, b: 255 },
      reliable: false,
      reason: "An ancestor uses a gradient, image, or pattern fill.",
    },
    isComponent: false,
    isInstance: false,
    isComponentSet: false,
    effects: [],
    ignoredIssueIds: [],
    hasVisibleTextChild: false,
    childCount: 0,
  },
];
